### ISSUE TITLE
`lean-action` template for `lake new/init`

### ISSUE THREAD

**Issue by austinletson** [leanprover/lean4#4606]
### Proposal

Add a template to `lake new/init` to allow users to automatically include a default continuous integration workflow that uses [lean-action](https://github.com/leanprover/lean-action).

With the `auto-config` improvement introduced by leanprover/lean-action#61, a call to `lean-action` with no inputs should be a reasonable default:

```yaml
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # uses lean action with all default input values
      - uses: leanprover/lean-action@v1-beta
 ```

Here are a few questions regarding implementation and user experience we need to align on:
- **How will the template interact with the existing templates and lake options?** Currently, users must choose one main template (std, exe, lib, math) and one file format (.lean, .toml) for the lakefile. Does adding a long option (e.g. `lake new --lean-action-workflow`) instead of a template make sense? @tydeu I thought you might be the best person to answer this.
- **How should the workflow triggers be configured by default?** I was thinking pushes and pull requests to the main branch. Alternatively,  we could keep it simple and trigger on a push it to any branch.

### Community Feedback

[link to relevant Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/lean-action/near/446192244)

Related to #3950 

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.
